name: Thomas Smith
description: Software developer in Ann Arbor, Michigan
url: https://thomasebsmith.github.io/blog/

baseurl: "/blog"
permalink: /:slug/
version: v1.2.0

plugins:
  - jekyll-feed

exclude:
  - README.md

sass:
  sass_dir: _scss
  style: expanded
