name: Thomas Smith's Blog
description: Software developer in Ann Arbor, Michigan

baseurl: "/blog"
permalink: /:slug/
version: v1.2.0

gems:
  - jekyll-feed

exclude:
  - README.md

theme: jekyll-theme-minimal
